<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de" sourcelanguage="en">
<context>
    <name>generals</name>
    <message>
        <location filename="../XTFLog_Checker_igcheck_dock_panel.py" line="44"/>
        <source>Show errors</source>
        <translation type="obsolete">Fehler anzeigen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_igcheck_dock_panel.py" line="45"/>
        <source>Show warnings</source>
        <translation type="obsolete">Warnungen anzeigen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="38"/>
        <source>Create layer</source>
        <translation>Layer erstellen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="41"/>
        <source>Cancel</source>
        <translation>Abbrechen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="44"/>
        <source>Show error log</source>
        <translation>Fehlerprotokoll anzeigen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="45"/>
        <source>Upload xtf-log file</source>
        <translation>Pfad oder URL einer XTF-Error-Log Datei auswählen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="46"/>
        <source>Show log for existing layer</source>
        <translation>Fehler-Log für vorhandenen Layer anzeigen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="47"/>
        <source>Only layers created with this plugin can be selected</source>
        <translation>Nur mit diesem Plugin erstellte Layer können ausgewählt werden</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="277"/>
        <source>No valid file</source>
        <translation>Keine gültige Datei</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="267"/>
        <source>Could not get a valid XTF-Log file from specified Url</source>
        <translation>Es konnte keine gültige XTF-Log-Datei von der angegebenen URL abgerufen werden</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="277"/>
        <source>No valid XTF-Log file at specified Path</source>
        <translation>Keine gültige XTF-Log-Datei unter angegebenem Pfad</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dock_panel.py" line="42"/>
        <source>Error log</source>
        <translation type="obsolete">XTFLog-Checker Fehlerprotokoll</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="413"/>
        <source>No Errors</source>
        <translation>Keine Fehler</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="210"/>
        <source>The selected XTF file contains no Ilivalidator-Errors, select another file.</source>
        <translation>Die ausgewählte Datei enthält keine Fehler vom Typ IliVErrors, wählen Sie eine andere Datei.</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="272"/>
        <source>Large file</source>
        <translation>Datei grösser als 5 MB</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="272"/>
        <source>Processing of large XTF-Log files might take a while</source>
        <translation>Die Verarbeitung grosser Dateien kann eine Weile dauern</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="100"/>
        <source>Unsupported file</source>
        <translation type="obsolete">Nicht unterstützte Datei</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="104"/>
        <source>Model {model_name} not supported.</source>
        <translation type="obsolete">Modell {model_name} wird nicht unterstützt</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="307"/>
        <source>No valid geometry</source>
        <translation>Keine gültige Geometrie</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="307"/>
        <source>No Point, Line or Surface Geometries found.</source>
        <translation>Keine Punkt-, Linien- oder Flächengeometrien gefunden</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="413"/>
        <source>The selected XTF file contains no igCheck-Errors, select another file.</source>
        <translation>Die ausgewählte XTF-Datei enthält keine igCheck-Fehler. Bitte wählen Sie eine andere Datei aus</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_igcheck_dock_panel.py" line="35"/>
        <source>Show infos</source>
        <translation type="obsolete">Infos anzeigen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_igcheck_dock_panel.py" line="57"/>
        <source>igCheck - Point Errors</source>
        <translation type="obsolete">igCheck – Punktfehler</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_igcheck_dock_panel.py" line="59"/>
        <source>igCheck - Line Errors</source>
        <translation type="obsolete">igCheck – Linienfehler</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_igcheck_dock_panel.py" line="61"/>
        <source>igCheck - Surface Errors</source>
        <translation type="obsolete">igCheck – Flächenfehler</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_igcheck_dock_panel.py" line="63"/>
        <source>igCheck Error log</source>
        <translation type="obsolete">igCheck-Fehlerprotokoll</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="120"/>
        <source>Unsupported error file version interlis2.4, ErrorLog24 iG/Check not supported yet - please contact developer if you are interested to add support for this model format!</source>
        <translation> Nicht unterstützte Fehlerdateiversion interlis2.4, ErrorLog24 iG/Check wird noch nicht unterstützt - bitte kontaktieren Sie den Entwickler, wenn Sie interessiert sind, Unterstützung für dieses Modellformat hinzuzufügen!</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="125"/>
        <source>Unsupported error file version interlis2.4, ErrorLog24 IliVErrors not supported yet - please contact developer if you are interested to add support for this model format!</source>
        <translation> Nicht unterstützte Fehlerdateiversion interlis2.4, ErrorLog24 iG/Check wird noch nicht unterstützt - bitte kontaktieren Sie den Entwickler, wenn Sie interessiert sind, Unterstützung für dieses Modellformat hinzuzufügen!</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="127"/>
        <source>Unsupported error file version interlis2.4, Model {model_name} / {model_sender} not supported yet - please contact developer if you are interested to add support for this model format!</source>
        <translation> Nicht unterstützte Fehlerdateiversion interlis2.4, Modell {model_name} / {model_sender} wird noch nicht unterstützt - bitte kontaktieren Sie den Entwickler, wenn Sie interessiert sind, Unterstützung für dieses Modellformat hinzuzufügen!</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="104"/>
        <source>Unsupported error file version , Model {model_name} not supported yet - please contact developer if you are interested to add support for this model format!</source>
        <translation> Nicht unterstützte Fehlerdateiversion, Modell {model_name} wird noch nicht unterstützt - bitte kontaktieren Sie den Entwickler, wenn Sie interessiert sind, Unterstützung für dieses Modellformat hinzuzufügen!</translation>
    </message>
</context>
</TS>
